version: '3'
services:
  app:
    container_name: cart-service
    image: behive/cart-service
    build: .
    volumes:
      - ".:/src"
    ports:
      - 3000:3000
    networks:
      - bridge
    environment:
      - PORT=3000
      - DATABASE_HOST=mongo:27017
      - DATABASE_NAME=cart
      - PRODUCTS_SERVICE_HOST=cart-products_service:3002
    depends_on:
      - mongo
      - cart-products_service
    stdin_open: true
    tty: true
  cart-products_service:
    container_name: cart-products_service
    image: behive/products-service
    ports:
      - 3002:3002
    networks:
      - bridge
    environment:
      - PORT=3002
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo/products-test
    depends_on:
      - mongo
  mongo:
    container_name: cart-mongo
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 3001:27017
    networks:
      - bridge
volumes:
  mongo_data:
networks:
  bridge: