version: '3'
services:
  app:
    container_name: cart-service
    image: behive/cart-service
    build: .
    volumes:
      - ".:/src"
    ports:
      - 3000:3000
    networks:
      - bridge
    environment:
      - PORT=3000
      - DATABASE_HOST=mongo:27017
      - DATABASE_NAME=cart
    depends_on:
      - mongo
    stdin_open: true
    tty: true
  mongo:
    container_name: cart-mongo
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 3001:27017
    networks:
      - bridge
volumes:
  mongo_data:
networks:
  bridge: