require_relative 'endpoints/open_cart'
require_relative 'endpoints/close_cart'
require_relative 'endpoints/get_cart'
require_relative 'endpoints/from_seller'
require_relative 'endpoints/add_product'
require_relative 'endpoints/remove_product'
